# Generated by Django 5.1.5 on 2025-02-03 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', code='invalid_username', message='Usernames can only contain letters and numbers.')]),
        ),
    ]
